# GCP container native load balancing using network endpoint groups
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tameduck-lb
spec:
  backend:
    serviceName: tameduck-lb
    servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tameduck-client-neg
spec:
  replicas: 10
  selector:
    matchLabels:
      app: tameduck-client-neg
  template:
    metadata:
      labels:
        app: tameduck-client-neg
        app.kubernetes.io/part-of: tameduck
    spec:
      containers:
      - name: client
        image: "ko://github.com/mkmik/tameduck/cmd/client"
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: TAMEDUCK_RATE
          value: "4"
        - name: TAMEDUCK_TARGET
          value: "http://35.244.193.33:80"
---
apiVersion: v1
kind: Service
metadata:
  name: tameduck-client-neg
  labels:
    app: tameduck-client-neg
spec:
  selector:
    app: tameduck-client-neg
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8082
